# Generated by Django 4.1.5 on 2023-04-23 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0002_alter_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='published_date',
        ),
        migrations.RemoveField(
            model_name='like',
            name='published_date',
        ),
        migrations.RemoveField(
            model_name='post',
            name='edited_date',
        ),
        migrations.RemoveField(
            model_name='post',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='post',
            name='published_date',
        ),
    ]
